name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Set Admin Password
    - name: Set Admin Password
      run: echo "TF_VAR_admin_password=${{ secrets.TF_VAR_admin_password }}" >> $GITHUB_ENV

    # Navigate to the Terraform directory before running commands
    - name: Initialize Terraform
      run: terraform -chdir=terraform init

    - name: Terraform Plan
      run: terraform -chdir=terraform plan -var="admin_password=${{ secrets.TF_VAR_admin_password }}"

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve -var="admin_password=${{ secrets.TF_VAR_admin_password }}"

    # Save Terraform State
    - name: Save Terraform State
      uses: actions/upload-artifact@v2
      with:
        name: terraform-state
        path: ./terraform/terraform.tfstate
